### PR TITLE
Controlsignals

### PR DESCRIPTION
**Pull request by jacobrosenthal**
* Add windows control signaling. 
* Fix RTS and DTR example, they're default high so to do a reset you actually set them false. (this is consistent with Chrome's serial handling). 
* Fix RTS and DTR defaults, and since false is significant alter the default flush in the set function.
* Add new control signal called Break which sets TX high. Added for both windows and unix/linux

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Heh. I think well need to change our jshint rules.

**Comment by phated** [comment]
:+1: using these APIs from the fork but would love them upstreamed

**Comment by voodootikigod** [comment]
Merging tonight

**Comment by voodootikigod** [comment]
first time trying to recompile with 0.12... grrr

*Chris Williams*

@voodootikigod <http://twitter.com/voodootikigod> | GitHub
<http://github.com/voodootikigod>

*The things I make that you should check out:*
SaferAging <http://www.saferaging.com/> | JSConf <http://jsconf.com/> |
RobotsConf <http://robotsconf.com/> | RobotsWeekly
<http://robotsweekly.com/>

Help me end the negativity on the internet, share this
<http://jsconf.eu/2011/an_end_to_negativity.html>.

**Comment by phated** [comment]
Node 0.12 isn't a thing. `nave usemain 0.10.36`

**Pull request merged**
