### PR TITLE
Backing out merge from #470

### PR DESCRIPTION
**Pull request by voodootikigod**

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
I dont believe we've had any reports of my #470 being problematic, We want to back out https://github.com/voodootikigod/node-serialport/pull/476

**Comment by voodootikigod** [comment]
I just had the wrong number you are right and this does back that one out.
I see you did the same. You pick on which one to merge

**Comment by jacobrosenthal** [comment]
Oh I see yeah its the correct commit in code. We'd have to clean the commit
message from yours, and I shouldnt merge my own code, so why dont you merge
mine?

**Comment by voodootikigod** [comment]
Deal

**Pull request closed without merging**
