### PR TITLE
Upgrade to nan v1.8.4 for io.js v2.0.0 compatibility

### PR DESCRIPTION
**Pull request by imyller**
Compiling fails with io.js `2.0.0`:

```
In file included from ../src/serialport.cpp:3:
In file included from ../src/serialport.h:5:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:181:66: error: too many arguments to function call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/-/.node-gyp/2.0.0/deps/v8/include/v8.h:4188:3: note: 'New' declared here
  static Local<Signature> New(
  ^
1 error generated.
```

This PR updates `nan` to version `~1.8.4` allowing installation of `node-serialport` with latest io.js.

### CODE REVIEW

**Comment by imyller** [comment]
Note: this PR does not address the usage of deprecated nan features causing compiler warning. This just allows installation and compilation with io.js v2.0.0

**Comment by imyller** [comment]
Referencing iojs/io.js#1620

**Comment by imyller** [comment]
Any way this (or similar) could be merged soon? Currently io.js `2.0.0` is not supported.

**Comment by voodootikigod** [comment]
Honestly I am not super worried about io 2.0.0 so until this can be confirmed to not affect node 0.10.x it will not be merged. And that has to be true for all platforms as outlined when io original support:

https://github.com/voodootikigod/node-serialport/issues/439

**Comment by reggi** [comment]
I'm getting the same error. 

Here's the full output:

https://gist.github.com/reggi/b107b1baab19431629b7

**Comment by imyller** [comment]
It seems that I have to update OpenEmbedded recipes in meta-iojs for 2.0.x before this gets in ;) 

I was waiting for serialport before updating packages there.

**Comment by reggi** [comment]
@voodootikigod any reason you left out OSX?

Ideally there was a service that would try to build a module on all of these platforms and report back on which fail :)

**Comment by voodootikigod** [comment]
@reggi hahah my bad. 

Remember for serial port its more than just build, we need to verify it works with an actual device.

**Comment by voodootikigod** [comment]
@imyller I am unsure what that means. I apologize if the response of having to make sure it doesn't break on other systems comes as a surprise, but this library is used in a tremendously broad range of implementation for production level things. I can't therefore willnilly update it and break all the things. I hope you understand.

**Comment by imyller** [comment]
@voodootikigod I meant that I wasn't going to release packages for OpenEmbedded/Yocto Linux for iojs 2.0.0 until I can confirm that node-serialport with recent nan is actually available.

So I'll release first and hope that node-serialport catches up later. 

No problems. I understand the need for due diligence.

**Comment by mattpodwysocki** [comment]
@voodootikigod seems to work fine on Windows 10 preview for io.js, node.js so at least you have nothing to worry about when it releases this summer.

**Comment by voodootikigod** [comment]
Merging cause why not? YOLO driven development, thanks to io.js

**Comment by sirwolfgang** [comment]
:+1:

**Comment by voodootikigod** [comment]
In Version 1.7.1

**Comment by imyller** [comment]
Thank you :+1:

**Comment by rektide** [comment]
Adding to the gist here, will there be support for Chakra Node? :hear_no_evil:

**Pull request merged**
