### PR TITLE
Update to nan 1.5.0 for iojs compat

### PR DESCRIPTION
**Pull request by rwaldron**
I don't have any other machines available to test on, so this was only tested on OSX

### CODE REVIEW

**Comment by voodootikigod** [comment]
Given the wide use of this by many people and it being a native module, for right now I am going to let this sit a couple days until it can be verified at a minimum on the following platforms:
[ ] Windows 8
[ ] Windows 7
[ ] Ubuntu Linux 14.10
[ ] Arch Linux
[ ] Raspbian Linux (Raspberry Pi)
[ ] Angstrom Linux (BBB)

If you have it working on them please report them as comments on this ticket. 

**Just a note:** I will not be breaking node.js compatibility with this change. Ideally this shouldn't be an issue, but If only one can be supported I am going to ensure existing users remain happy for the time being.

**Comment by timoxley** [comment]
https://github.com/iojs/io.js/issues/456

**Comment by rwaldron** [comment]
@voodootikigod awesome, thanks for that list btw :)

**Comment by No9** [comment]
Ubuntu build is fine will run some testing over the next few days to confirm.
This needs to be on song for the battle royale!! 
http://london.nodebots.io/

**Comment by No9** [comment]
Tested Windows 7 iojs v1.0.2 
Looks good to me
https://twitter.com/dhigit9/status/556439502538178561

**Comment by gorhgorh** [comment]
tried the raspberry pi and had a strange error, output is [here](https://gist.github.com/gorhgorh/a8c5b73319b8f42c8a3c).
installing the current npm version ran fine, and i reran npm run install in them.
i do not have grunt and all installed yet on this pi but i can install them if needed

**Comment by gorhgorh** [comment]
Update, I cloned the original repo and made the same edits as you (ie bump nan to 1.5.0) and it worked like a charm

**Comment by No9** [comment]
@gorhgorh that output looks like you didn't `git checkout iojs-compat` after you cloned the repo. 

Also can you confirm it was raspbian OS for the sake of good house keeping :)

**Comment by gorhgorh** [comment]
I just check the said branch, it contains one the same changes (the bump of nan). 
and yep I confirm this is on a standard raspbian image

**Comment by voodootikigod** [comment]
@gorhgorh did you check both node and IO.js working?

**Comment by voodootikigod** [comment]
Make sure you utilize
```
npm install --build-from-source
```
when building on your platform.

**Comment by nodebotanist** [comment]
I would test recommend we test BBB with Debian-- it's now the default / preinstalled OS

**Comment by fivdi** [comment]
@gorhgorh it looks like you [tested with node.js v0.10.33](https://gist.github.com/gorhgorh/a8c5b73319b8f42c8a3c#file-gistfile1-txt-L30). AFAIK nobody has gotten io.js to run successfully on the Pi yet. See io.js issue [Getting 'illegal instruction' error on armv6](https://github.com/iojs/io.js/issues/283).

**Comment by fivdi** [comment]
I agree with @nodebotanist regarding Debian on the BBB. There are issues there too though. See [io.js armv7l build isn't working on the BeagleBone Black](https://github.com/iojs/io.js/issues/349)

@voodootikigod perhaps it's not all that important if io.js + serialport currently doesn't work on a particular platform. The PR from @rwaldron could still be merged if node.js + serialport works on all required platofrms. If io.js + serialport works on some platforms with the PR then it would still be worth merging.

**Comment by gorhgorh** [comment]
as far as i know io.js is not yet supported on arm, i just checked that the bump was not affecting the node users so yes i agree @fivdi

**Comment by fivdi** [comment]
There are "offical" io.js ARM release for ARMv7 available at iojs.org. For example, [iojs-v1.0.2-linux-armv7l.tar.gz](https://iojs.org/download/release/v1.0.2) functions with Ubuntu 14.04 on the BBB (but not on the default / preinstalled Debian.)

**Comment by Hamper** [comment]
work with gentoo + iojs v1.0.2

**Comment by fivdi** [comment]
node-serialport compiles and functions as expected with io.js on a BeagleBone Black running Ubuntu 14.04.1 LTS (GNU/Linux 3.14.26-ti-r43 armv7l). The output of the install can be seen below. The Angstrom and Debian images available at [http://beagleboard.org/latest-images](http://beagleboard.org/latest-images) are probably used by most people. Unfortunately, these images are not up-to-date enough for running or compiling io.js.

```
ubuntu@arm:~/src/serialport$ iojs --version
v1.0.2
ubuntu@arm:~/src/serialport$ npm install "git://github.com/rwaldron/node-serialport.git#iojs-compat"
-
> serialport@1.4.10 install /home/ubuntu/src/serialport/node_modules/serialport
> node-pre-gyp install --fallback-to-build

child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/ubuntu/src/serialport/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
  CXX(target) Release/obj.target/serialport/src/serialport_poller.o
  SOLINK_MODULE(target) Release/obj.target/serialport.node
  SOLINK_MODULE(target) Release/obj.target/serialport.node: Finished
  COPY Release/serialport.node
  COPY /home/ubuntu/src/serialport/node_modules/serialport/build/serialport/v1.4.10/Release/node-v42-linux-arm/serialport.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory `/home/ubuntu/src/serialport/node_modules/serialport/build'
serialport@1.4.10 node_modules/serialport
├── bindings@1.2.1
├── sf@0.1.7
├── async@0.9.0
├── nan@1.5.1
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
└── node-pre-gyp@0.5.31
ubuntu@arm:~/src/serialport$ 

```

**Pull request merged**
